site:
  name: High Tide Aviation
  site: "https://flyhightide.com"
  base: "/"
  trailingSlash: false

  googleSiteVerificationId: orcPxI47GSa-cRvY11tUe6iGg2IO_RPvnA1q95iEM3M

# Default SEO metadata
metadata:
  title:
    default: High Tide Aviation
    template: "%s | High Tide Aviation"
  description: "High Tide Aviation offers premier aerial tours across two spectacular locations: Southport, NC, and St Simons Island, GA. Choose from our diverse tour options including both airplane and helicopter rides in Southport, and exclusive airplane tours in Georgia. Each flight is an opportunity to take in breathtaking landscapes and historical landmarks, guided by our experienced pilots who ensure a safe and memorable experience. Perfect for tourists, photography enthusiasts, and anyone looking to celebrate a special occasion. Book your next adventure with High Tide Aviation and see the Southeast coast from a new perspective!"
  robots:
    index: true
    follow: true
  openGraph:
    site_name: High Tide Aviation
    images:
      - url: "~/assets/images/high-tide-aviation-team-southport.jpg"
        width: 1200
        height: 628
    type: website
  twitter:
    handle: "@onwidget"
    site: "@onwidget"
    cardType: summary_large_image

i18n:
  language: en
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 6

    post:
      isEnabled: true
      permalink: "/%slug%" # Variables: %slug%, %year%, %month%, %day%, %hour%, %minute%, %second%, %category%
      robots:
        index: true

    list:
      isEnabled: true
      pathname: "blog" # Blog main path, you can change this to "articles" (/articles)
      robots:
        index: true

    category:
      isEnabled: true
      pathname: "category" # Category main path /category/some-category, you can change this to "group" (/group/some-category)
      robots:
        index: true

    tag:
      isEnabled: true
      pathname: "tag" # Tag main path /tag/some-tag, you can change this to "topics" (/topics/some-category)
      robots:
        index: false

    isRelatedPostsEnabled: true
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: "G-LLPZRNV0EP" # or "G-XXXXXXXXXX"

ui:
  theme: "system" # Values: "system" | "light" | "dark" | "light:only" | "dark:only"

  tokens:
    default:
      fonts:
        sans: InterVariable
        serif: InterVariable
        heading: InterVariable
      colors:
        default: rgb(50 60 70)
        heading: rgb(0 0 0)
        muted: rgb(50 50 50 / 66%)
        bgPage: rgb(255 255 255)
        primary: rgb(0 19 53)
        secondary: rgb(0 44 81)
        accent: rgb(100 76 13)
    dark:
      fonts: {}
      colors:
        default: rgb(229 236 246)
        heading: rgb(247, 248, 248)
        muted: rgb(229 236 246 / 66%)
        bgPage: rgb(3 6 32)
        primary: rgb(1 97 239)
        secondary: rgb(1 84 207)
        accent: rgb(109 40 217)
